### ISSUE TITLE
Generating passwords?

### ISSUE THREAD

**Issue by k0nsl** [microvb/otp-thing#2] opened 2017-02-04 16:44 UTC
Hi,

I installed the application without any issues to speak of, but I'm wondering: where exactly do I generate passwords? I only glanced over the `README.md` file and understood this to be a sort of fancy version of `passwordgenerator.net`.

Thanks in advance.

**Comment by dkrusky** [comment] 2017-02-23 02:30
This app does not generate passwords.  It is the framework for a portal which you can plug your code in without having to deal with all the login/password/etc stuff.

You can create new users by going to the **Administrator > Accounts > Add** page. The password is whatever you decide to use as a password. :)

Closing this as this is not a bug.

**Closed as completed** 2017-02-23 02:41 UTC
